# Generated by Django 5.0.1 on 2024-01-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osnova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok',
            name='kartinka',
            field=models.ImageField(upload_to='images'),
        ),
    ]
